lib/strs_web/router.ex
defmodule StrsWeb.Router do
  use StrsWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", StrsWeb do
    pipe_through :browser

    get "/", PageController, :index
    get "/users", UserController, :index
    resources "/users", UserController

    get "/login", SessionController, :new
    post "/login", SessionContoller, :create
    resources "/session", SessionController, only: [:new, :create]
    get "/sessions", SessionController, :delete
  end

  # Other scopes may use custom stacks.
  # scope "/api", StrsWeb do
  #   pipe_through :api
  # end
end

lib/strs_web/views/layout_view.ex
defmodule StrsWeb.LayoutView do
  use StrsWeb, :view
end

lib/strs_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Strs · Phoenix Framework</title>
    
    <link rel="icon" type="image/png" sizes="32x32" href="<%= Routes.static_path(@conn, "/images/favi/favicon-32x32.png") %>">
    <link rel="icon" type="image/png" sizes="16x16" href="<%= Routes.static_path(@conn, "/images/favi/favicon-16x16.png") %>>
    <link rel="manifest" href="/site.webmanifest">
    <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="theme-color" content="#ffffff">
    
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#" style="width:10%">
    <img  style="width:80%" src="<%= Routes.static_path(@conn, "/images/strslogo/STRS-Bold.png") %>" alt="Phoenix Framework Logo"/>
  </a>
  <%= if logged_in?(@conn) do %>
    
      <button type="button" class="btn btn-danger">
        <%= link "Users", to: Routes.user_path(@conn, :index) %>
      </button>
    
  <% end %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    
  </div>
  <ul class="navbar-nav mr-auto">
      <%= if logged_in?(@conn) do %>
        <li class="nav-item">
        
          <span class="navbar-text">
            <img  width="30" height="30" src="<%= Routes.static_path(@conn, "/images/avatar2.jpg") %>" alt="User"/>
          </span>
          <button type="button" class="btn btn-primary">
            <%= current_user(@conn).first_name <> " " <> current_user(@conn).last_name %>
          </button>
          
        </li>
        <li class="nav-item">
          
          <button type="button" class="btn btn-danger">
            <%= link "Logout", to: Routes.session_path(@conn, :delete) %>
          </button>
        </li>
      <%= else %>
        <li class="nav-item">
          <%# <a class="nav-link" href="#" style="padding-right:1.5rem">Register</a> %>
          <%= link "Register", to: Routes.user_path(@conn, :new), class: "btn btn-secondary" %>
        </li>
        <li class="nav-item">
          <%= link "Login", to: Routes.session_path(@conn, :new), class: "btn btn-primary" %>
          <%# <a class="nav-link" href="#" style="padding-right:1.5rem">Log in</a> %>
        </li>
      <% end %>
  </ul>
</nav>
    <main role="main" class="container">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <%= render @view_module, @view_template, assigns %>
    </main>
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>